### ISSUE TITLE
Change year based routing to use "undergraduate-2014" style

### ISSUE THREAD

**Issue by thybag** [unikent/of-course#125]
Hello,

Just a note to look at changing the ug/year routes to use a undergraduate-xxxx style so we can better differentiate undergraduate/xxxx (year) from undergraduate/xxxx (ID) going forward.

Although this isn't really an issue now, its worth fixing else we will likely encounter it next year.

Carl

**Comment by eg270-unikent** [comment]
@cs462-unikent is this still going to be an issue?

**Comment by eg270-unikent** [comment]
I'm going to close this issue as we have 4 digit IDs in place now, e.g. http://www.kent.ac.uk/courses/undergraduate/2016/1384/applied-sport-and-exercise-science so don't think this is required anymore.
