### ISSUE TITLE
Too much space between H1 and H2

### ISSUE THREAD

**Issue by frithassell** [unikent/of-course#131]
With the padding underneath H1 on top of the padding above H2 the white space left is a bit too roomy: http://www.kent.ac.uk/courses/undergraduate/profiles/index.html
I've tried taking the H2 out of the <div> but this it doesn't reduce it:
http://www-test.kent.ac.uk/courses/undergraduate/profiles/index.html

**Comment by eg270-unikent** [comment]
I don't think this is still an issue as we rolled out a load of styling in the past year.
