### ISSUE TITLE
Courses/undergrad site QA bugs and inconsistencies

### ISSUE THREAD

**Issue by jt353-unikent** [unikent/of-course#297]
Luca reviewed some UG course pages and fed back on some bugs and inconsistencies he spotted.
They are mostly small issues except for the bug where multiple items are selected in the left-hand nav - this should be tackled first.

Document with QA comments:
https://www.dropbox.com/s/zpqiqkyuxnqa6z2/Courses%20website%20QA%20-%20JT%20-%20020913.docx

-----------------------

From: Jonathan Thirlwell <j.thirlwell@kent.ac.uk>
Date: Mon, 2 Sep 2013 11:35:07 +0100
To: Luca Macis <G.Macis@kent.ac.uk>
Cc: "rs-consultants@kent.ac.uk" <rs-consultants@kent.ac.uk>, Bonnie Ferguson <B.Ferguson@kent.ac.uk>, "is-webdev@kent.ac.uk" <is-webdev@kent.ac.uk>
Subject: Re: Courses/undergrad site

Hi Luca,

Thanks for the feedback. This is very useful – I'll create a Github issue and as we develop in Daedalus for the PG work, we can tackle these bits. I've added some comments to your document. 

I've focussed mainly on course pages themselves and the PG homepage, I have yet to tackle the broader content pages, but your feedback helps to make a start.

Thanks,
Jonathan

From: Luca Macis <G.Macis@kent.ac.uk>
Date: Fri, 23 Aug 2013 12:02:45 +0100
To: Jonathan Thirlwell <j.thirlwell@kent.ac.uk>
Cc: "rs-consultants@kent.ac.uk" <rs-consultants@kent.ac.uk>, Bonnie Ferguson <B.Ferguson@kent.ac.uk>
Subject: Courses/undergrad site

Hi Jonathan,
 
Based on what we discussed a little this morning I decided to have a quick look through the courses/undergrad 2014 pages. I have suggested some minor modifications to different aspects of the site. Most of them are incredibly minor and are most likely bits that were missed during the development process.
 
Please feel free to have a look through and it may be useful to get some of the devs on aspects of my feedback that you agree with. I would consider most of them bugs so could be considered BAU. Others are a items to consider.
 
Again, any questions please feel free to pop by J
 
Thanks,
Luca

**Comment by eg270-unikent** [comment]
Going to close this as the document doesn't exist any more and @gm268-unikent has now left the organisation.
