### ISSUE TITLE
Postgraduate courses banner - make a link

### ISSUE THREAD

**Issue by jt353-unikent** [unikent/of-course#336]
Could the Postgraduate Courses banner also be a link to the PG homepage? 
It feels like you want to click it on a mobile.

**Comment by eg270-unikent** [comment]
@jt353-unikent the reason we didn't was because of inconsistency with other sites. Although we did implement this for the 50th site.

**Comment by eg270-unikent** [comment]
@aw285-unikent do you think this would be useful as well? Might be worth doing some user testing

**Comment by aw285-unikent** [comment]
@eg270-unikent I will defer to Jonathan on this one as I'm not sure what's standard practice on mobile?

**Comment by eg270-unikent** [comment]
Jonathan wanted us to go ahead with this. Unfortunately it didn't make it out of the sprint backlog last week as it was low priority. It will need to be looked at at a later date. I'm removing the milestone for this.

**Comment by jt353-unikent** [comment]
Had a conversation with Carl - this issue is not longer relevant as we are moving towards the new theme design.
