### ISSUE TITLE
Daedalus logo is slightly lighter than Chronos logo

### ISSUE THREAD

**Issue by jt353-unikent** [unikent/of-course#340]
The Daedalus Kent logo is a bit lighter than the Chronos logo and jumps slightly when switching between Chronos and Daedalus pages.

I've prepared a slightly darker version which is closer to the colour on Chronos.

Thanks
Jonathan

![logo-comparison](https://f.cloud.github.com/assets/4367005/1158124/025f8cdc-1fae-11e3-91a9-2adf029380fe.jpg)

![unikentlogo 2x](https://f.cloud.github.com/assets/4367005/1158094/99572a9c-1fad-11e3-969b-186d1688bcb5.png)

**Comment by eg270-unikent** [comment]
@jt353-unikent this no longer appears to be an issue?
