### ISSUE TITLE
Floating apply links and Key Informaton panel

### ISSUE THREAD

**Issue by jt353-unikent** [unikent/of-course#355]
Can we see if the right-hand Apply links and Key Information panel can float as the user scrolls down on the page as per original concept?

Thanks
Jonathan

**Comment by eg270-unikent** [comment]
@jt353-unikent this may cause issues when we try to do responsive. Can we user test to see if this would be useful to users?

**Comment by eg270-unikent** [comment]
Have spoken with Jonathan who thinks this is no longer relevant
