### ISSUE TITLE
Course finder - courses appearing too low on the page?

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#404]
Hi as I've been using the new course search more, particularly on my laptop, I've been wondering if the filter options and course list appear too low down on the page as they are below the fold? I wondered if the 'Courses A-Z' title, the UG and PG tabs and the search box could be made to fill less space at the top of the page, so that the courses appear higher up the page? Might be worth looking into at some point?

http://www.kent.ac.uk/courses/undergraduate/search/

**Comment by eg270-unikent** [comment]
@jt353-unikent can you take a look at this one please? It may be that when we have the new theme that this will no longer be an issue.

**Comment by eg270-unikent** [comment]
@aw285-unikent this is currently on test. I've asked @jt353-unikent to review the 'Choose a course that's right for you. Learn more' - I think an underline would make it more clear but perhaps it needs some user testing.

**Comment by aw285-unikent** [comment]
@eg270-unikent Yes, I thought the same earlier - when I first saw it, I thought it was a link rather than a drop down for some reason.

**Comment by eg270-unikent** [comment]
Rolled out this morning, awaiting cache to clear. @jt353-unikent please review design based on our feedback ^^
