### ISSUE TITLE
Subject leaflets

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#413]
As EMS (Michelle Rowe)

I would like the subject leaflet links for UG and PG to appear in the Key Facts box

To increase findability (see email below). 

I said I would let Michelle know if and when this would be possible - please could you let me know? - Thanks Angela. 

Hi

I have just had a quick look at a couple of pages and notice the subject leaflets are really quite hidden.  Is it possible for them to be moved to the key facts box for download?

This is also the case on the UG pages, so is it possible for the link to be moved here too?  This is particularly important for UG as the prospectus has been stripped back and we are directing students to the website.

Thanks.

Michelle

**Comment by eg270-unikent** [comment]
@aw285-unikent is this something you wish to pursue?
The subject leaflets currently appear on the enquiry tab

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent I think I will close this for now and re-open it if we get similar feedback in the future.I think the layout of the enquiries tab has changed since this was first opened and they are more prominent.
