### ISSUE TITLE
PG subject leaflet index

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#416]
Hi would it be possible to have a PG subject leaflet index like the one for UG please?
http://www.kent.ac.uk/courses/undergraduate/leaflets/index.html
Marketing would really like to push the subject leaflets and make them more prominent, 
Thanks
Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this looks to have been done http://www.kent.ac.uk/courses/postgraduate/leaflets/index.html Can it be closed?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent yes I have linked it into the site. Many thanks.
