### ISSUE TITLE
Add RDP and GSA info to PG course pages

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#465]
Mary would like information about the Global Skills Award (for PGT) http://www.kent.ac.uk/graduateschool/skills/programmes/gsacurrent.html 

and the Researcher Development Programme (for PGR)  http://www.kent.ac.uk/graduateschool/skills/programmes/tstindex.html

To be added to the programmes pages. 

Consider whether global fields could be used to acheive this rather than schools manually adding content.

**Comment by eg270-unikent** [comment]
@aw285-unikent is still something you're still looking to add?

**Comment by aw285-unikent** [comment]
Hi Edele, could we have two immutable fields please? One that outputs on research programmes, and one that outputs on taught programmes. The content would be the last heading to output on the 'study support' tab eg. 

[on taught programmes] 

<heading> Global Skills Award <heading>

[Field copy] blah....

[on research programmes] 

<heading> Researcher Development Programme<heading>

[Field copy] blah....

It would also be good to have a checkbox under the page admin section to stop this from outputting when schools request this. 

many thanks

Angela

**Comment by aw285-unikent** [comment]
@eg270-unikent forgot to tag you (above)

**Comment by eg270-unikent** [comment]
@aw285-unikent OK have added to sprint backlog.

**Comment by gjmh-unikent** [comment]
@aw285-unikent 
what about courses that are Taught-research?
should we display either/both?

**Comment by aw285-unikent** [comment]
@gjmh-unikent i would go with neither... I don't know enough about those courses to know if either programme is relevant but schools could always add it manually if it is.
