### ISSUE TITLE
Adding images to course pages 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#492]
As EMS

We would like to add on-brand images to our course pages which represent the course, 

to make the pages more visually appealing. 

@jt353-unikent and @tlm-unikent met with Lesley Farr to discuss. Record below.

Hi Angela,

Tanith and I met with Lesley yesterday to find out about image usage on course pages. Lesley has provided a PDF gallery with a selection of both Kent and stock images (this will be made available to everyone from the new branding site) and Zarina apparently has a selection of the images used in the printed prospectus.

There will not be enough images to go around for all the courses to all have a different image. What we were thinking is that perhaps to begin with [courses with suitable images could have them] It may make sense for some courses to use the same image, but where it doesn't we could gradually add more images over time.

Here is the prototype demo I've been experimenting with:
http://pantheon.app.www-dev.kent.ac.uk/jt353/school-snippet/daedalus.html

I think the process of adding/managing images still needs clarity:
Selection - How will images be selected? Will we have a fixed image area on the course pages so that they always appear in the same area? I think this may be good to start with. Are we going to have a title accompanying images? All images will need to have alt text  - how will we ensure these are added?
Preview/Quality check - We'll provide initial images, but will schools ultimately have access and decided image use? In which case how will the suitability/quality of images used be checked before going live? Guidelines over image preparation and use will be needed and I think a quality check past EMS before going live would be good if this is feasible.
 Hosting - Where will the images be hosted, will they be uploaded via the programmes plant or is there another way to manage hosting? This is one for me to follow up with my team.
Thanks,
Jonathan

**Comment by eg270-unikent** [comment]
@aw285-unikent is this one still blocked?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent yes - it's something we'd still like to do but there are issues with the image stock and resource required to get this off the ground. Do you want me to close this and re-open or leave it blocked? I don't mind either way.

**Comment by gjmh-unikent** [comment]
finally done!
