### ISSUE TITLE
Problems with PG xcri feed  

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#529]
I'm looking at the PG xcri feed and noticing a few issues. These aren't pressing issues at the moment but may become so in the future so I am logging them on the backlog as a record:

```
- <description> not pulling in main subject overview text; only pulling in programme overview text. 
- <start> is hardcoded and not using data from the programmes plant 
- <end> hardcoded and wrong
- <cost> fees info missing 

```

**Comment by aw285-unikent** [comment]
@eg270-unikent @jna-unikent Hello, I've just got to this one above - I think this can be closed as you've looked at the XCRI feed. However, please could you confirm if the description is now pulling in the main subject overview and not the programme overview text. So that's the text that outputs under the 'overview' tab and not the 'course structure' tab on the front end. 

Thanks

Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent I've checked this and we are  pulling in the main subject overview text for the XCRI feed. We haven't changed this for UG but as prospects will only be pulling in the PG programmes this should not be an issue in the short-term.
