### ISSUE TITLE
Version of Course Summary Snippet for International Newsletter

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#542]
As Nathan Crouch 

I would like to adapt the Courses Summary Snippet to create a version that automatically displays all new courses offered by the University.
 
We send out regular newsletters to our overseas agents directing them to our agent news page and I’d like to include the snippet on the page so agents can, at any time, check to see the new courses available without us having to source the information and manually add it to the page. Is it possible to amend the snippet so that rather than pulling in courses by department, it does so based on when the course was added to the Programmes Plant (i.e. to show all programmes added within the last 3 months)?
 
Deadline: By late August if possible to coincide with the relaunch of our agent comms.

@lrhm-unikent @eg270-unikent

**Comment by eg270-unikent** [comment]
@aw285-unikent this seems to be a duplicate of #689, can this issue be closed?

**Comment by aw285-unikent** [comment]
@eg270-unikent yes I'll close this one - must have forgot I'd added this.
