### ISSUE TITLE
Distance learning filter

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#595]
As EMS Marketing (Fiona Holden)

I would like a 'distance learning' filter on the course finder as well as part-time/full-time. 

So that those wishing to study by distance learning can easily find options open to them. 

AW to clarify with Fiona if this is for PG only.

**Comment by jna-unikent** [comment]
@aw285-unikent Just to clarify, this story is to add a new drop down to the PG search page (https://www.kent.ac.uk/courses/postgraduate/search), that will filter for attendance mode.

Currently the attendance mode field in Programmes Plant has these options:
 - Distance with attendance
 - Distance without attendance
 - Campus

So users would be able to filter by those three options.

Let me know if that sounds right.

**Comment by aw285-unikent** [comment]
Hi Justice, let me chat to Fiona (who originally requested this feature) and get back to you. No rush on this one,

Thanks

Angela

**Comment by aw285-unikent** [comment]
Hi @jna-unikent 

Hi Justice, 
I have agreed the functionality for the distance learning filter with Fiona in Marketing now. 

On the PG course filter only, could the 'All study modes' drop-down have an additional item called 'Distance learning'. So you would have three choices on that drop-down:
- Full-time
- Part-time
- Distance learning

When you select 'Distance learning' on the filter, anything with the 'Attendance mode' of 'Distance with attendance' and 'distance without attendance' (eg with these checkboxes checked in the backend on the 'attendance mode field') would appear on the list. 

This would mean that some programmes would appear. 

Does this make sense? 

many thanks

Angela
http://www.kent.ac.uk/courses/postgraduate/search

**Comment by eg270-unikent** [comment]
PR: https://github.com/unikent/of-course/pull/730

**Comment by eg270-unikent** [comment]
This has been rolled out
