### ISSUE TITLE
Module Synopses not pulling through to the programme pages

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#603]
@lrhm-unikent @eg270-unikent 
Hello, I have noticed that some module synopses are not pulling through to the programme pages. See for example most modules on the MArch:
https://www.kent.ac.uk/courses/postgraduate/186/master-of-architecture#!structure
I have seen this on other programmes here and there. There are synopses in the modules catalogue. 
Thanks
Angela

**Comment by aw285-unikent** [comment]
@eg270-unikent I don't know if this was resolved or not but looking at artchitecture MArch (which was moved here: http://www.kent.ac.uk/courses/undergraduate/889/architecture#!structure all the module synopses are outputting. So I will close this for now and re-open if I see any other examples.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent yes it was resolved, it was an issue with how we were pulling in the modules.
