### ISSUE TITLE
Add stylised links/buttons for 'Accommodation' and 'Open Days' under key facts

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#605]
As EMS, 

I would like to add stylised links/buttons under the key facts for:

'Accommodation' (UG ONLY)
and
'Open days' (UG AND PG)

With editable links in the backend. 

So users can easily access this info. 

The open days info on the 'enquire' tab is getting lost and so I think we should just have a button instead. 

Currently, we have no accommodation link which I think we should have.

**Comment by eg270-unikent** [comment]
Angela would like us to proceed with adding the above as per Jonathan's design

**Comment by aw285-unikent** [comment]
@eg270-unikent yes please

**Comment by jna-unikent** [comment]
@aw285-unikent did you see my msg about the Accommodation and Open days links being created as overridable fields? Just so that by default, all programmes have the same links unless overridden. To prevent the case where nothing will display if they're not filed in.

Unless of-course you'd prefer nothing being displayed if those fields aren't filled in.

**Comment by eg270-unikent** [comment]
@aw285-unikent these changes are currently on test. We haven't added links to the images as we're not sure where these should point to?

The images and text are pulled from a file located in courses/postgraduate/links/learnmore.html (replacing 'post' with 'under' in the URL for undergraduate)

Some images really don't work very well and we'll need to be careful about which ones we choose. We've chosen some random images from various parts of the website for now

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent we're doing a rollout to live on Tuesday 24th to fix the fees tracking. However, the pull request contains these changes to the course page design - should these be removed from the deploy?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent yes please can you remove this from the deploy. I need to review this on test and the comment above but unfortunately can't give this proper attention right now. Can we leave deploy until after the prospectus launch please? It shouldn't matter if the change is made post-launch.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this has been rolled to test today. Can you please review and let me know if you want to come over to go through how it works?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent thanks - it looks realyl good. Are you free on Monday to go over this with both @frithassell Fritha and I at the same time please? We can pop over to you?

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent I'm afraid I'm not in on Monday. Is there another day next week that you both can do?

**Comment by aw285-unikent** [comment]
@eg270-unikent how about Wed?

**Comment by eg270-unikent** [comment]
@aw285-unikent that's fine, I'll pop something in your calendars.

**Comment by eg270-unikent** [comment]
@aw285-unikent This has been rolled out today. Are you happy for this issue to be closed?

**Comment by aw285-unikent** [comment]
@eg270-unikent sorry - missed this. Closing.
