### ISSUE TITLE
Feedback at the R&M forum: Course summary snippet. 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#615]
@lrhm-unikent @eg270-unikent @msf4-unikent 
 We received the following feedback (from schools) on the course summary snippet at the Recruitment & Marketing forum: 

- Could the standard programme (eg the single hons or programmes without time in industry/abroad) appear at the top of the snippet?

- Could the summary snippet have location tabs, for schools teach the same programme at different campuses (not sure if this has been requested before?)

I said I would pass this on. 

Thanks

Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent do you know if people are still requesting this? Our advice to Tizard was to use the tab snippet and use multiple course summary snippets inside each tab snippet.

**Comment by aw285-unikent** [comment]
@eg270-unikent I don't get much feedback on the snippet so I'm not sure if this is still an issue. I presume the tab solution is a good workaround Happy to leave this for now.
