### ISSUE TITLE
Displaying modular fees

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#628]
As Finance, 

I would like to be able to display fees that are billed per module on the course pages fee slider and have the data come from the same source file as the other fee data. 

To ensure the fee info is accurate and consistent.

**Comment by aw285-unikent** [comment]
@eg270-unikent another one that I'm not sure about the status off, so will discuss with adam later in the week.

**Comment by eg270-unikent** [comment]
@aw285-unikent did you discuss this one with Adam?

**Comment by aw285-unikent** [comment]
@eg270-unikent yes i think they resolved this by adding tabs to the finance table. will close.
