### ISSUE TITLE
Flexible tabs on course summary snippet

### ISSUE THREAD

**Issue by edelarose** [unikent/of-course#636]
As a publisher,

I want to have the flexibility to change the tabs of the course summary snippet

so that I can organise courses based on different criteria
- [ ] location
- [ ] single/joint/European programmes
- [ ] PG Taught/PG Research tabs
- [ ] Year abroad/Year in Industry
- Advanced snippet that allows multiple options separated in the parameter table with semicolons (e.g. undergraduate; single-honours).
- Let the publishers name the tabs to prevent IS having to provide further development for custom situations

@jt353-unikent are you able to provide some design input as to whether these tabs will work with the new theme? We also need to give some consideration to schools who may use too many tabs.

**Comment by jna-unikent** [comment]
Also see: FP#676905

**Comment by jt353-unikent** [comment]
Concept for additional filters for school course snippet
![course-snippet-filter](https://cloud.githubusercontent.com/assets/4367005/9041425/d87d8d10-39ff-11e5-9259-7d41c92145e3.jpg)

**Comment by aw285-unikent** [comment]
@eg270-unikent @jt353-unikent Hello thanks for this - is the 'More filters' bit on the side an alternative suggestion to having 'Showing all locations, all awards, all course types' or is this in addition to?

**Comment by eg270-unikent** [comment]
@aw285-unikent we are unable to find anyone using a filterable summary snippet, do you know of any schools that are?

**Comment by aw285-unikent** [comment]
@eg270-unikent I didn't know there was a filterable summary snippet?
