### ISSUE TITLE
Ordering courses on summary snippet

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#637]
As a publisher,

I want the ability to order the courses on the summary snippet differently

so that I can apply different scenarios that work best for my school

- [ ] default remains alphabetical order
- [ ] order by standard course first (followed by different varieties of that course e.g. Film should appear before Film with a year abroad)

**Comment by jna-unikent** [comment]
@aw285-unikent Do you know of any examples of courses where a department needs to change the ordering on their courses? I'm struggling to find examples to work with.

**Comment by aw285-unikent** [comment]
Hi @jna-unikent I'm sorry, it was so long ago that I am struggling to remember the use case for this one. I'm not sure whether this story originated from feedback we got about the snippet in one of the recruitment and marketing forums or from web solutions working with schools. 
Looking at the arts school website, the standard film course does come before the Year Abroad course and I can't think of any other situation where schools would need to re-order. Skip it? Or have you done too much work on it already?
http://www.kent.ac.uk/arts/undergraduate.html

**Comment by jna-unikent** [comment]
@aw285-unikent no I have merely looked into it. happy to skip it and revisit if it pop its head again. I'm closing it. Thanks.
