### ISSUE TITLE
Strategic Leadership course: No Modules outputting. Apply link not working. 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#640]
@eg270-unikent 
Hello, just reporting that no modules are outputting for this programme. The POS code viewable in the backend and there are modules associated with the programme in SDS. Also, the apply link is not working. THere is an MCR code in the backend. The enquiry link seems to be working fine. 
http://www.kent.ac.uk/courses/postgraduate/757/strategic-leadership-and-medical-education#!structure

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent SITS have updated the strategic leadership course to have the programme ID. However, it is pulling through 2 deliveries for the part-time course, but one seems to be incorrect. I've questioned SITS on this and asked them to remove the delivery containing the wrong MCR.

**Comment by eg270-unikent** [comment]
Apply link is now working but still no modules

**Comment by eg270-unikent** [comment]
Modules are now present @aw285-unikent are you happy for this to be closed?
