### ISSUE TITLE
Xcri snippet: pulling in suspended programmes

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#641]
As School of Arts

I would like the ability to exclude suspended and withdrawn programmes from the courses summary snippet. 

So that we don't present these courses as 'running' to prospects.

**Comment by eg270-unikent** [comment]
@aw285-unikent do you want us to exclude these programmes by default?

**Comment by aw285-unikent** [comment]
@eg270-unikent yes please

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing
