### ISSUE TITLE
Review changes: Returning to index when click 'Edit this programme'. 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#652]
When you review changes, and click 'edit this programme' it takes you to the programme index/homepage instead of the page you want to edit.

**Comment by aw285-unikent** [comment]
@eg270-unikent @cs462-unikent is there any chance this one could go on your next rollout please?

**Comment by eg270-unikent** [comment]
@aw285-unikent yes it's already been merged so is on the list for Tuesday's rollout.
Thanks,
Edele

**Comment by aw285-unikent** [comment]
@eg270-unikent @frithassell Was this one fixed? If so I'll close.

**Comment by eg270-unikent** [comment]
Yes it should be fixed now.
