### ISSUE TITLE
School snippet - spacing issue, CSS needs to be slightly updated

### ISSUE THREAD

**Issue by jt353-unikent** [unikent/of-course#653]
- CSS needs to be adjusted for the fees panel. Text is using a larger line-height for Chronos.
- Spacing between the callout and the bottom image needs to be increased

Example here:
http://pantheon.app.www-dev.kent.ac.uk/websolutions/kbs/courses/ug/accountingfinance.html#!overview

From FP 586284

**Comment by eg270-unikent** [comment]
This has now been rolled out:

https://github.com/unikent/pantheon/pull/1058
