### ISSUE TITLE
Clone 2015 UG prospectus to create 2016 UG prospectus in PP.

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#655]
As EMS

I would like IS to clone the 2015 UG prospectus to create 2016 UG prospectus in programmes plant for 2 Feb. 

So EMS and school admins can make content changes prior to publication .

**Comment by eg270-unikent** [comment]
This has been done on live and test.

We copy the live revisions of programmes so any 2015 programmes awaiting review in the PP inbox won't get copied across.
