### ISSUE TITLE
Modules not showing accounting and management -  MSc

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#659]
@eg270-unikent 
Hi Edele, KBS have noted that the modules are not showing for:

http://www.kent.ac.uk/courses/postgraduate/742/finance-and-management#!structure

They have set the module session to 2016 (by overriding the 2015 default session). The POS code is correct and there are modules in v-pos for the 2016 session. 

Please could you take a look?

Many thanks

Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent I'm currently rerunning the module import task to see if the modules appear after that. This usually takes a couple of hours to run as it iterates through all programmes. I will update you as soon as the task is finished.

**Comment by eg270-unikent** [comment]
This should now be fixed. Closing.
