### ISSUE TITLE
International Security and the politics of Terror - 120 credit option

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#661]
@eg270-unikent 
Belinda in EMS reports:

 
"The above programme (Programmes plant ID 48) should be available for on-line applicants, however, there is no way to select this option from the on-line prospectus.  The MCR code is PIST000105MA-FD and is showing as in use.
 "

I can see the delivery in the backend of the programmes plant and on the fee slider - it's just not outputting on the apply listing. PLease could you look at this? 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent I believe this issue has now been resolved and was caused by the caching issue on the new server. Can we close?

**Comment by aw285-unikent** [comment]
@eg270-unikent Yes looks resoved so will close.
