### ISSUE TITLE
Report of discrepancies between SITS description and Programme title

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#662]
@eg270-unikent @lrhm-unikent 
As EMS 

I would like a Report of discrepancies between the SITS description and Programme title

So that Phil Shore may amend discrepancies on SITS where required to ensure consistency.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent is this report showing the difference between the Programme title (in the programmes plant) vs the delivery description which we pull from SITS?

For example: 
- Programme title: Actuarial Science - PDip
- SITS Description: Actuarial Science - PDip - full-time at Canterbury?

I'm not sure what this report will resolve as evision uses the delivery description, so we are unable to change the programme title to match this as a programme can have multiple deliveries. I guess we could do a report of delivery names against their associated programme title to see whether they are similar.

**Comment by aw285-unikent** [comment]
@eg270-unikent Hi Edele, Yes I understand that to be the report we need. The idea is that the description would be changed in SITS where it is wrong - the programme pages have the right (Marketing titles).

The problem we are trying to address are those reported by KBS and Adam which I just forwarded to you eg the programme showing the wrong title on the fees table, and on the enquries tab, fees drop down (course pages) and application form.

**Comment by eg270-unikent** [comment]
Sent via email today.
