### ISSUE TITLE
Unpublishing programme not having desired effect

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#663]
Hi, on Tuesday I unpublished European Public Policy MA - today it was still live, although could not be searched for. The status had reverted to new. Is it possible to look at this and change the status of unpublished programmes to 'unpublished' please? I have since deleted this programme but it's still live http://www.kent.ac.uk/courses/postgraduate/53/european-public-policy

**Comment by aw285-unikent** [comment]
The course above has been removed from the website now but please could you look at the unpublishing issue?

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this has been done and is pending rollout (https://github.com/unikent/programmes-plant/pull/834).

**Comment by eg270-unikent** [comment]
This has been rolled out. Closing

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent http://www.kent.ac.uk/courses/undergraduate/197/psychology-and-sociology - I tried this on this programme but it's still live and I did it a couple of hours ago.

Thanks

Angela

**Comment by gjmh-unikent** [comment]
ok think i have got to the bottom of this now, looks like we were not nuking one of the many many caches correctly.
I have a fix ready and will roll out in a suitable booking slot, we will nuke all the caches at the same time to fix any similar issues with supposedly unpublished programmes and it should not happen again *crosses fingers*.

see:  https://github.com/unikent/programmes-plant/pull/843

**Comment by aw285-unikent** [comment]
@gjmh-unikent Hello, has this one been resolved? Thanks Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent the fix for this went live over a month ago, are you still having issues?

**Comment by aw285-unikent** [comment]
@eg270-unikent not that I know of. I will close it and reopen if there are any problems. I don't have a programme to test at the moment.
