### ISSUE TITLE
Headings on cells that are not links

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#678]
Please could you look at the spacing on the 'choose your course', 'how to apply' and 'undergraduate funding' headings on this page and similar cells:

https://www.kent.ac.uk/courses/undergraduate/part-time/

The spacing works fine if the heading is a link but we don't need these headings to be links. So I removed the links and the spacing squished up (and slightly more on the last two headings I think?). 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent I'll ask @jt353-unikent to review.

**Comment by jt353-unikent** [comment]
The spacing is all squished up. @aw285-unikent @eg270-unikent Could you adjust the paddings/margins slightly to be similar to the screenshot?

I noticed the markup is also incorrect. Headings should use heading tags - at the moment they are only styled to look like headings, this could be improved too. Images are also inaccessible, can we please add alt text to them? 

![image](https://cloud.githubusercontent.com/assets/4367005/6572271/be202b72-c708-11e4-83b3-b53a0e2f6f21.png)

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this is on www-test but we need to roll out the same change to live https://www-test.kent.ac.uk/courses/undergraduate/part-time/ - can you check on test and ensure you're happy with this?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent looks great thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this has now been fixed on live. Closing
