### ISSUE TITLE
Add 'Course structure overview' field to UG programmes plant area

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#681]
@eg270-unikent 
AS EMS 

I would like a 'course structure overview' field on the UG programme page form and for this to output in the same way as the 'course structure overview' field outputs on the PG prorgamme pages. 

so content editors can provide additiional information abut the structure of the course, which currently they cannot do.

**Comment by eg270-unikent** [comment]
@aw285-unikent this is what the Module intro text does at the moment for UG. Do you want it to be renamed?

**Comment by aw285-unikent** [comment]
@eg270-unikent strictly, the modules intro field is supposed to be for overriding the modules disclaimer    with an adjusted version of the disclaimer but I think we might have strayed from this to get more details in about the course structure. We'll carry on with that for now as we all know to check that the right disclaimer is in place, as do schools. I'll close this one.
