### ISSUE TITLE
Reorder enquire and order a prospectus tab

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#683]
From #647104

Following our discussion with @aw285-unikent this afternoon, Jonathan has agreed to look at various designs for how we can present this tab better.

See example below. 
![example](https://cloud.githubusercontent.com/assets/6604537/7351560/ceb14fdc-ecfd-11e4-8164-eaa2fa425aaf.PNG)

- [x] Should we remove the indentation for BSc (Hons) and the bullet point beneath it?
- [x] Replace open days with #605 (only for of-course, not for snippet)
- [x] Move download prospectus link under resources
- [x] Move contacts underneath resources
- [x] Remove related courses from tab (leave carousel of related courses in place)

**Comment by jt353-unikent** [comment]
@aw285-unikent  @egormley 

I've prepared two examples below. 

http://pantheon.app.www-dev.kent.ac.uk/jt353/school-course-snippet/index.html#!enquire

Idea with the subject leaflet information simplified into a single link:

http://pantheon.app.www-dev.kent.ac.uk/jt353/school-course-snippet/index-2.html#!enquire

**Comment by eg270-unikent** [comment]
@aw285-unikent this has now been done but we are having issues with our pantheon repository on Github so were unable to roll out the snippet. We are hoping to resolve this issue by the end of this week.

**Comment by eg270-unikent** [comment]
This was rolled out a while ago so I'm closing this issue.
