### ISSUE TITLE
Review logic of results on course search

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#685]
As EMS 

We would like to see if it's possible to review how results appear on the quick course search. (When you type in 'international' on the PG version of the search, the courses do not file in aphabetical order and group similarly named programmes together). 

So the results are alphabetical /
![international-coursesearch](https://cloud.githubusercontent.com/assets/2726241/7432470/43e8c4c2-f020-11e4-9ae8-9ff184d97f94.jpg)
 group similar programmes together.

**Comment by gjmh-unikent** [comment]
Having looked at how this is currently implemented i would not recommend any changes.

The search results are ranked by "relevance" a metric devised by taking into account a number of factors and searching in a number fields not displayed in the results.

Whilst in the particular case shown in in your screenshot, grouping or sorting the results alphabetically would make it easier to read in many other cases it would push a more relevant result down the list.

i have made a minor adjustment that will better group identically named courses within the results without effecting the "relevance". how does this look?

![screen shot 2015-06-16 at 16 49 06](https://cloud.githubusercontent.com/assets/9929369/8187513/f75c5938-1447-11e5-91db-17aa6fa506d2.png)

**Comment by aw285-unikent** [comment]
@gjmh-unikent Hi Greg, thank looks much better thank you :)

Angela

**Comment by aw285-unikent** [comment]
@gjmh-unikent @eg270-unikent Hello, was this one rolled out? Just wondering if it can be closed?

Thanks
Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent yes this was part of pantheon and has been rolled out
https://github.com/unikent/pantheon/pull/1282
