### ISSUE TITLE
Add campus to course quicksearch and Programmes Plant tables

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#687]
As EMS,

I would like the campus field to be added to the quicksearch for courses and to the table in the Programmes Plant

so that I can quickly see the location of the course

- [x] Add campus to PP programmes table (for both UG and PG)
- [x] ~~Investigate whether it is possible to add location search to the courses CSE Course location will be removed from the programme title so Film (Paris) will be Film with a location of Paris. Search for 'Paris' should return all courses taught at Paris.~~

**Comment by eg270-unikent** [comment]
Following our discussion with Angela and Sam today we have agreed to:

- [ ] Change page title to have Course Name - Award - Location - University of Kent
- [ ] Move location to be a h2 inside the header (so it's grouped with h1)
- [ ] Add location to course finder - needs UX input from @jt353-unikent but Angela has requested that the location is visually separate from the course and award (either in bold or more right-aligned)

**Comment by gjmh-unikent** [comment]
proposed design from @jt353-unikent 

![locations_in_search](https://cloud.githubusercontent.com/assets/9929369/7913126/1a9d182c-0865-11e5-81de-53d251bb59bf.png)

**Comment by eg270-unikent** [comment]
@aw285-unikent this has been rolled out today. Can you check that you're happy with this?
