### ISSUE TITLE
New course snippet

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#689]
As Nathan Crouch

I would like a snippetised version of:

http://www.kent.ac.uk/courses/postgraduate/new/

http://www.kent.ac.uk/courses/undergraduate/new/

For use on:

The International Student homepage and on our agent page.

http://www.kent.ac.uk/internationalstudent/

http://www.kent.ac.uk/international/overseas-representatives.html

So that we can promote new courses to students and also, so that our international agents can do the same. 

[I am adding this on for Nathan and am happy to prioritise it with our other work when we next have development time but it might be best to speak to Nathan directly about the finer details when the time comes].

**Comment by eg270-unikent** [comment]
We have spoken with ID today. They also would like the ability to configure the snippet to only output those courses with 'Science without borders' enabled in the Programmes Plant.

**Comment by eg270-unikent** [comment]
This is with Nathan Crouch for review.
Please can we update the snippet https://github.com/unikent/of-course/issues/689 with all available filtering options?

**Comment by eg270-unikent** [comment]
Can we check the snippet for this? I think what I was referring to is adding some help text to the snippet to let international development know what the filters are
