### ISSUE TITLE
Refering users to 2015 UG prospectus from 2016 prospectus pages. 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#692]
As EMS, International Development

I would like a line to appear under the main content of each UG 2016 programme page saying:

"This is a 2016 entry programme. Would you like to view [eg Accounting and Finance and Economics] for 2015 entry?"

Which wil work in the same way as that on the 2015 pages eg 

https://www.kent.ac.uk/courses/undergraduate/2015/1/accounting-and-finance-and-economics

But will be more discreet (no yellow box, just text). 

To help users realise that they can still apply for courses starting in 2015 should they wish to (eg international students and part-time)

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent - is this what you would like?
![example](https://cloud.githubusercontent.com/assets/6604537/7679349/b62c0810-fd53-11e4-874b-5408aa0142fc.PNG)

**Comment by aw285-unikent** [comment]
HI @eg270-unikent the text is great but please could it go at the bottom of the page. Perhaps just above the related courses bar? 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent not sure this really works design wise for courses that don't have the related courses bar:

![example](https://cloud.githubusercontent.com/assets/6604537/7679817/4e716ee0-fd58-11e4-8a23-101eb81f4555.PNG)

**Comment by aw285-unikent** [comment]
@eg270-unikent OK. Let's go with the first version instead, Many thanks

Angela

**Comment by eg270-unikent** [comment]
This was rolled out this morning. @aw285-unikent - can you ensure you're happy with this.

**Comment by aw285-unikent** [comment]
@eg270-unikent Thanks Edele. Just realised the link's not going to the 2015 entry

https://www.kent.ac.uk/courses/undergraduate/1/accounting-and-finance-and-economics

Sorry to be a pain but if you have to do more work on this, is it possible to drop the message to the bottom as per example 2 above - looking at it live and with the location change too, it looks a bit cluttered at the top of the page. It's if's an issue, we'll just wait until after clearing when this will come off anyway. 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent - I've fixed the link on test but we'll need another booking slot to roll the fix out to live. If we can wait to roll out until Thursday, I can make the change to display at the bottom of the page and that can go live on Thurs as well.

**Comment by aw285-unikent** [comment]
@eg270-unikent perfect thanks!

**Comment by aw285-unikent** [comment]
@eg270-unikent @msf4-unikent Hi I'm really sorry, I've been asked to keep this message at the top of the page after all. Long story. *ducks and disappears into the half-term sunset*.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent I've put in another PR to move the banner back to the top. https://github.com/unikent/of-course/pull/700

**Comment by aw285-unikent** [comment]
@eg270-unikent Thank you - there were competing demands, marketing wanted it at the bottom originally but admissions wanted it at the top.

**Comment by eg270-unikent** [comment]
This has been rolled out today. @aw285-unikent happy for this issue to be closed?
