### ISSUE TITLE
Add administrative school to programmes plant page titles

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#697]
As Sam Charman @STC21-UniKent 

I would like the page titles for the programme page web pages to be in the format::

 ‘History - BA (Hons) - University of Kent – School of History’

instead of 

'History - BA (Hons) - University of kent' 

That is, with the administrative school's name tagged onto the end. 

So that I can filter programmes by schools within google analytics. 

- [x] Add to event tracking on courses pages
- [x] Add to event tracking on course snippet

**Comment by aw285-unikent** [comment]
@eg270-unikent @msf4-unikent @STC21-UniKent 
Hi there, can you speak to Sam before actioning this one as he has some different ideas about how this could be done for the purposes of Google analytics. 

However, I would still like to discuss adding the locations to the page title as per my email to Mark yesterday to mitigate any potential SEO issues with removing the locations from the programme titles. 
Eg. Page titles would be in the format: 
'History - BA (Hons) –University of Kent – Paris and Canterbury' 
Thanks

Angela

**Comment by eg270-unikent** [comment]
For clarity, this should be adding to the event tracking for GA only.

The apply/enquire/order links (including those on the interim apply page) should have the ga event include the administrative school and the location data for the programme (both UG & PG)

**Comment by eg270-unikent** [comment]
Hi @STC21-UniKent currently there is tracking on the following links:

- Apply link on main courses page
- Fees dropdown
- Next/Apply via UCAS button on the interim apply page
- Enquire tab:
  - Enquire online link
  - Order a prospectus link
  - Download a prospectus link

There is no tracking on the following:
- enquire or order a prospectus on main course tabs (these are tracked on enquiries tab as above)
- Enquire tab:
  - Download a subject leaflet link
  - Read our student profile
  - Contact email links
  - school websites links

Do you want me to add the administrative school to all existing events? Do we need any additional event tracking on those links which are not currently tracked?

**Comment by eg270-unikent** [comment]
Hi @STC21-UniKent this was rolled out today for the courses pages. There should already be tracking on the snippet as of last Thursday - 4th June.

**Comment by STC21-UniKent** [comment]
Thanks Edele, had a quick look and all seems good.

All the best

Sam
