### ISSUE TITLE
programme not showing in course search

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#705]
@eg270-unikent 
Hello, I noticed this programme is not showing in the course search but is live when you go to the URL directly. 

I'm not sure why this would be. Please could you take a look? 

Many thanks
Angela

https://www.kent.ac.uk/courses/postgraduate/359/international-masters-in-finance-investment-and-risk
https://webtools.kent.ac.uk/programmes/2015/pg/programmes/edit/359

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent, what browser are you using? I'm not experiencing this issue in Chrome:

![screenshot](https://cloud.githubusercontent.com/assets/6604537/8008855/98639710-0b9c-11e5-8e0c-45356318b41c.PNG)

**Comment by aw285-unikent** [comment]
Very odd. It definitely wasn't showing earlier (would have been using chrome of FF) - I checked several times using both course searches to check I hadn't missed it. Hey-ho, it's there now! Thanks

Angela
