### ISSUE TITLE
Add information on how to apply to the apply page

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#706]
As EMS 

I would like to add information on how to apply to the apply page as per Jonathan's @jt353-unikent  design. 

[Still need to discuss how this would work for programmes that link straight to SITS (eg where there is only one award and it can only be studied part-time or full-time but not both. Also need to discuss the content of this information). 

So that users have more contextualising information about how to apply and the application process before they start their application.

**Comment by jt353-unikent** [comment]
![course-application-details](https://cloud.githubusercontent.com/assets/4367005/8057737/d338d9ba-0eab-11e5-9811-62046482e023.jpg)

**Comment by eg270-unikent** [comment]
@aw285-unikent @jt353-unikent where should 'the application process' link to?

**Comment by jt353-unikent** [comment]
Hi @aw285-unikent - I just wanted to check, are these correct application links to link to from the course application page?

Undergrads:
https://www.kent.ac.uk/courses/undergraduate/apply/how.html

Postgrads:
https://www.kent.ac.uk/courses/postgraduate/apply/

**Comment by aw285-unikent** [comment]
@jt353-unikent yes they would be the best links. I did start looking at adding information to these pages to prepare part-time UG and FT and PT PG students before they complete the online application form (for example, to tell them how many references they need etc) but that has fallen by the wayside slightly as I'm so short-staffed at the moment.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent will this need to apply to Full-time UG atypical courses as well?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent no I think it's best to leave it off those courses.

**Comment by eg270-unikent** [comment]
This didn't make it out of the sprint backlog, @aw285-unikent this probably needs to be re-prioritised for BAU

**Comment by eg270-unikent** [comment]
@aw285-unikent do you want to proceed with adding this text to the of-course apply pages?

If so do you need to be able to update this text easily (i.e. does it need to be in Programmes Plant) or can we hard code it?

**Comment by aw285-unikent** [comment]
Yes please – I can only see us needed to change the link, so I’m happy for you to hardcode it and then update the links if we ever need to. Or add it to the progs plant. Whatever’s easiest for your team.

Thanks

Angela


_____________________________________________________________________________
Angela Watson | Digital Communications Manager | Digital Communications Unit, Publishing Office |
Enrolment Management Services | University of Kent |
Room G46, The Registry, Canterbury, Kent, CT2 7NZ, UK
Tel: +44 (0)1227 827450 | E-mail: a.watson@kent.ac.uk | Fax: +44 (0)1227 827077

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this change was deployed live this morning. Please can you check it's working as expected and let me know if there's any issues with this change?
