### ISSUE TITLE
Add space for an alumni profile/quote on the 'careers' tab. 

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#707]
As EMS 

I would like to allow schools the potential to allow/or link to graduate/alumni profile or quotes on the careers tab. 

[very much on the backlog - needs to be discussed further within EMS].

**Comment by eg270-unikent** [comment]
@aw285-unikent have you had a chance to discuss this further in EMS?

**Comment by aw285-unikent** [comment]
@eg270-unikent Will close this one for now as it would be way down the line before we could implement this.
