### ISSUE TITLE
Make subject categories file in alphabetical order

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#708]
@eg270-unikent 

AS EMS

I would like the subject categories on 'All subject categories' course filter drop-down list to file in alphabetical order. 

http://www.kent.ac.uk/courses/postgraduate/search

To help with selection. 

Not sure if this is more of a bug than a 'story' as UG seems to be OK. PLease could you take a look in the next BAU? 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing.
