### ISSUE TITLE
Link to new student blogs from course pages

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#709]
As EMS 

I would like a link to student blogs on our course pages as of mid-september when Sam @STC21-UniKent  launches the blogs. 

To drive traffic to the new content. 

[Sam has some mock ups here: ] 
![blog-graphic1](https://cloud.githubusercontent.com/assets/2726241/8130614/bdd0049c-110b-11e5-8f2a-2a5807f238fe.gif)
![blog-grpahic2](https://cloud.githubusercontent.com/assets/2726241/8130615/bf4bf5a6-110b-11e5-9546-f9b4eb75247c.gif)

**Comment by STC21-UniKent** [comment]
I'll keep you updated on the launch date, I'm hoping to go live in mid-sept, but all depends how much content I get from the bloggers over the summer. Early October may be better once they are back.

I can keep you updated.

Thanks

Sam

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent and @STC21-UniKent where were you envisioning these panels being located on the course pages?

**Comment by aw285-unikent** [comment]
HI @eg270-unikent yes somewhere on the course pages. We're open to design ideas.

**Comment by eg270-unikent** [comment]
@STC21-UniKent can you arrange a meeting with Jonathan to discuss as he's very keen to help you out with these designs.

**Comment by jt353-unikent** [comment]
Discussed with Sam and Angela @aw285-unikent  @STC21-UniKent that we'd try a bullet list link the the student blogs below the Student Experience promo as they are trying to do similar things. We'll also include a strong promotion to the student blogs on the new Student Experience page design.

![course-student-profile](https://cloud.githubusercontent.com/assets/4367005/9034229/f54f5ebc-39c5-11e5-8bcf-ce231e899c5d.jpg)

**Comment by eg270-unikent** [comment]
@jt353-unikent do you know what the link is going to be?

**Comment by jna-unikent** [comment]
@jt353-unikent @aw285-unikent do have a look at the implementation on www-test: http://www-test.kent.ac.uk/courses/undergraduate/181/computing. Happy to go live if you are...

**Comment by aw285-unikent** [comment]
Hi @jna-unikent thanks for this - we don't need to roll this out until September - is that OK? (@stc21-unikent too)

**Comment by eg270-unikent** [comment]
This has been rolled out

**Comment by eg270-unikent** [comment]
@aw285-unikent and @STC21-UniKent I thought this had already been rolled out but it'll be rolled out tomorrow

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing.

**Comment by aw285-unikent** [comment]
@eg270-unikent Hi Edele, re-opening. Please could the link also go on PG? on the 'Why study at Kent?' button at the bottom. https://www.kent.ac.uk/courses/postgraduate/201/visual-anthropology

Many thanks

Angeka

**Comment by eg270-unikent** [comment]
HI @aw285-unikent for this section, the same styles apply for UG and PG. Therefore, you just need to add the link to the postgraduate/links/learnmore.html page. I've done this for you and pushed it live this morning.

**Comment by aw285-unikent** [comment]
@eg270-unikent Ah I see, sorry and thank you!
