### ISSUE TITLE
Tool tips for awards?

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#710]
As EMS 

We would like to consider how to guide users to information about what each award (MPhil, PhD, MA, etc. involves). 

So that users can access this information. 

Users were confused about the awards in the user testing. We have this info in our 'Types of Degree' section but this is virtually impossible to find from the programme pages due to the lack of left hand nav:

https://www.kent.ac.uk/courses/postgraduate/types/index.html

eg
https://www.kent.ac.uk/courses/postgraduate/types/taught.html
https://www.kent.ac.uk/courses/postgraduate/types/research.html

Other info in this section is also hidden which may be an issue for users and from a compliance point of view. 

[

**Comment by eg270-unikent** [comment]
@aw285-unikent Greg did some work for this last week which is currently on test http://www-test.kent.ac.uk/courses/undergraduate/1/accounting-and-finance-and-economics

**Comment by aw285-unikent** [comment]
@eg270-unikent thanks Edele - we are working on the pages these link to but this can be rolled out in the meantime. Thanks
Angela

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing.
