### ISSUE TITLE
Set part-time overseas fees to NA

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#714]
AS EMS 

We would like part-time overseas fees to be set to N/A on the course pages. 

To discourage needless applications from overseas students who cannot study part-time due to visa restrictions. 

[There may be another ticket for this story or it may be attached to a wider issue] but I am adding it again in case it isn't].

**Comment by jna-unikent** [comment]
@aw285-unikent I'm supposing this should apply to the departmental snippets too?

**Comment by aw285-unikent** [comment]
@jna-unikent yes please

**Comment by jna-unikent** [comment]
@aw285-unikent sure thing.

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing.
