### ISSUE TITLE
Clearing button on UG 2015 course pages

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#715]
@eg270-unikent @msf4-unikent 

As EMS

For Clearing (7th July onwards), I would like the 'Apply, enquire or order a prospectus' box on the right-hand side of the 2015 UG course pages to be replaced by a box that says 'Is this course in Clearing?'. This wil point to a URL that can be set and changed by the EMS web team via the programmes plant. 

[The URL will go to a Clearing vacancies html page that generates a list of vacant courses which are pulled from SITS. We need the URL to be editiable in the programmes plant, in case of emergency where we would need to link to a different page). ]

So that users can easily find check if the course they are interested in is in Clearing.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this will need to be done during our BAU days next Monday and Tuesday, but it can be rolled out on Tues 7th.

I'll add this to the backlog for BAU with a relatively high priority

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent I am adding more clearing related stories - was going to email you once I've finished.

**Comment by gjmh-unikent** [comment]
@aw285-unikent i have added a "clearing vacancies link" field here:
https://webtools.kent.ac.uk/programmes/2016/globalsettings/edit
please configure as necessary and make live.

You can do this now as it will not be used until the 7th.

**Comment by aw285-unikent** [comment]
@gjmh-unikent Thanks Greg. I have added the link 

https://evision.kent.ac.uk/ipp/clearingvacancylist.htm

and published. Just checking it is definitely OK that those are the 2016 global settings when the link in on the 2015 propsectus? 

Thanks

Angela

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent the evision link should be updated in the 2015 global settings for this to work. I've edited this on live but this will need published when we go live tomorrow.
