### ISSUE TITLE
Review banners on 2015 and 2016 UG course pages to direct users to clearing

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#717]
@eg270-unikent @msf4-unikent 
As EMS 

I would like to review the current banners on the 2015 and 2016 UG course pages to direct users to Clearing where appropriate. To go live for Clearing on 7 July. 

[Please could we discuss this one to finalise the story. It would be good to get web dev's thoughts].

**Comment by gjmh-unikent** [comment]
can you clarify what is required/desired for this? which banners are we referring to?

**Comment by aw285-unikent** [comment]
@gjmh-unikent 

Yes, sure. To explain the background: when Clearing opens (7 July), Clearing applications need to be encouraged to view the 2015 undergraduate prospectus course pages rather than the 2016 ones. 

Therefore, last year we had a yellow banner on the following UG 2016 course pages:

http://www.kent.ac.uk/courses/undergraduate/
http://www.kent.ac.uk/courses/undergraduate/search

Directing Clearing applicants to view the 2015 prospectus + suitable links. 

We also had a yellow banner at the top of each UG 2016 course page that referred them to the relevant 2015 course page (or to the course search if there wasn't a course with the same course ID in 2015). 

We already have a message on the 2016 UG pages which say (eg...

'This is a 2016 entry programme. Would you like to view Accounting and Finance and Economics for 2015 entry?'

See: http://www.kent.ac.uk/courses/undergraduate/1/accounting-and-finance-and-economics

So I think this needs to be more prominent (yellow box, overlay, etc - JT could have a think?) and changed to something like:

<heading> Applying for Clearing?
<p> This is a 2016 entry programme. Clearing applicants and others planning to start in 2015 should view Accounting and Finance and Economics for 2015 entry.'

The 2015 UG prospectus already has some yellow banners eg:

http://www.kent.ac.uk/courses/undergraduate/2015/search/

http://www.kent.ac.uk/courses/undergraduate/2015/1/accounting-and-finance-and-economics

So I think the text just needs to change to:

This is a 2015 entry programme. Clearing applicants should view this page. Those wishing to start in 2016 can view Accounting and Finance and Economics for 2016 entry.'

Or something like that. It would be good to get your team's input on the best execution of this. 

I hope that makes sense but I am in tomorrow if you'd like to chat about it. 

Thanks

Angela

**Comment by jt353-unikent** [comment]
@aw285-unikent @gjmh-unikent 
Something like this?


![image](https://cloud.githubusercontent.com/assets/4367005/8435166/b574c644-1f47-11e5-8d37-2a0184761d57.png)

**Comment by aw285-unikent** [comment]
@jt353-unikent @gjmh-unikent Yes please can we go with the banana design... very on-brand. 

Actually, I think the other one would be fine!

**Comment by aw285-unikent** [comment]
@jt353-unikent @gjmh-unikent Would it be possible to remove the break between 'This is a 2016 programme' and 'Clearing applicants..'
