### ISSUE TITLE
2016 PG prospectus clone

### ISSUE THREAD

**Issue by eg270-unikent** [unikent/of-course#723]
As Angela,

I want the PG prospectus clone to be done on the live server on 25th August 2015

so that schools can see and edit their pages in preparation for the 2016 Prospectus going live on 14th September.

- [x] Please can we check the clone mechanism on 24th August (as part of BAU) to ensure everything goes smoothly for 25th August.

The email to schools was:
"As with previous years, we will clone the 2015 version of the prospectus to create the 2016 one for you to edit. Once the clone has been made, you will need to update programme changes on both prospectus years until the 2015 PG prospectus is ‘switched off’ on 14 September. 
  
Ideally, we would aim to clone the prospectus around three weeks before the launch date. This means that you don’t have to duplicate changes for too long, but it also gives us (Publishing) time to update the ‘National rankings’ information using the info in the printed prospectus. If anyone would struggle with updating their pages within this timetable, please could you let me know? We will not be updating entry requirements (as these are no longer in the PG printed prospectus) so individual schools will need to check these are correct. "

**Comment by jna-unikent** [comment]
Hello @eg270-unikent, @aw285-unikent I have run the PG rollover script on www-test. Could you check that all looks good? https://webtools-test.kent.ac.uk/programmes/2016/pg/programmes

**Comment by aw285-unikent** [comment]
@jna-unikent @eg270-unikent it looks good to me thanks except that the preview is not working and the programme deliveries aren't pulling through but not sure if they should be at this stage? Could you let me know please?

**Comment by jna-unikent** [comment]
@aw285-unikent The preview didn't work because the overridable fields weren't rolled over, I forgot it. I've manually published it for now but I'll remember to do it on live tomorrow. I believe deliveries are run nightly so that should come through by morning.

**Comment by aw285-unikent** [comment]
@jna-unikent great thank you :)

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent I've checked www-test this morning and the previews are working but the deliveries are not. I believe this is because we hadn't yet set up the task to run PG 2016 deliveries overnight. I'll run this manually and let you know.
It's probably worth us holding off on cloning the PG prospectus on live until we're happy that the deliveries are coming through on www-test. I'll update you as soon as the task has finished running

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent there should now be deliveries for PG 2016 on test. I've setup a CRON so that we pull in the deliveries for 2016 when we do the rollover on live.
We're currently looking at doing the rollover on the live system, I'll update you again when it's complete.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent we have now rolled over the prospectus on live and re-ran the import for the deliveries. 

Thanks,
Edele

**Comment by aw285-unikent** [comment]
Hi @eg270 - many thanks. I will email schools to tell them they can start editing their 2016 programmes.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent are you happy for this issue to be closed or would you rather leave it open incase schools have feedback?

**Comment by aw285-unikent** [comment]
@eg270-unikent could you keeep it open for a bit please? I had one person email about having problems logging in but not sure if that was user error - waiting to hear back.

**Comment by aw285-unikent** [comment]
@eg270-unikent I didn't hear back so I will just close this for now. Thanks 

Angela
