### ISSUE TITLE
Notes field on programme pages

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#724]
As EMS superusers

We would like a 'notes' field in the superuser view of the programme pages

so we can add notes about the status of a programme.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent how much text do you envisage people entering into this field?

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent about 500 words maximum. it's so superusers can leave each other notes so we can delete old notes to get it within the word count when using it.
