### ISSUE TITLE
Ability to remove progammes from the inbox

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#740]
@eg270-unikent 
As EMS

I would like the ability to remove programmes from the plant inbox 

So I can remove programmes that cannot/do not need to be published and keep the inbox in order.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent can you let me know what the use case is for this? Is it to reject programmes?

**Comment by aw285-unikent** [comment]
@eg270-unikent 
Hi Edele, the use case is to clear the inbox of programmes that can't be process for various reasons. 

For example:
- Comparative Literature (Paris) - is currently suspended so we can't approve the changes and make it live. 
- All the updates from Kim Britnell at the bottom of the inbox - we're not going to publish as they are for the 2015 entry prospectus which will be coming down soon. 
- International economic law - the programme has been deleted but it's stuck in the inbox.

**Comment by gjmh-unikent** [comment]
ok so if we simply add an "Approve" button at teh bottom of the review page. that will remove its entry from your inbox but will not publish it to live, would that work?

**Comment by aw285-unikent** [comment]
@gjmh-unikent yes I think that would work. thanks

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent this has been rolled to test, can you review and ensure you're happy for it to be rolled live?

**Comment by aw285-unikent** [comment]
@eg270-unikent I tested this on two programmes and it worked well thanks. Happy for it to be rolled out.

**Comment by eg270-unikent** [comment]
Hi Angela, we're going to roll progs plant and of-course live tomorrow morning so this will be rolled out then.

**Comment by eg270-unikent** [comment]
Rolled out today. Closing.
