### ISSUE TITLE
Removal of UG 2015 prospectus

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#744]
@eg270-unikent we will be removing links to the UG 2015 prospectus on 18th September. I forget it you usually take down the web pages too? Please could you remind me?

Also, what's Harry's github ID, please? I assume I should start tagging both of you now?

**Comment by eg270-unikent** [comment]
@aw285-unikent No we keep the pages as we did for the UG 2014 prospectus but CC will need to update the megamenu etc.  We'll just need to update the config file to turn clearing off - I've already put a system booking in for this.

Harry hasn't setup his github account yet. I've asked him to do this today. He'll be hk284-unikent once done.

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent we turned off clearing this morning. However, with the UG prospectus we still have the banner 'This is a 2016 entry programme. Would you like to view <course> for 2015 entry?' Do you want this to be removed?

**Comment by aw285-unikent** [comment]
@eg270-unikent yes please

**Comment by eg270-unikent** [comment]
Hi @aw285-unikent as we're outside of our booking slot now (it ended at 10am), we would need to put another booking in place to remove this text. Can it wait until Monday? If not, I'll need to speak to the Head of IT Support to try to get an emergency booking to roll live today. Change is already on www-test.

**Comment by aw285-unikent** [comment]
@eg270-unikent Hi Edele, I'm really sorry but I don't think it can wait until Monday because the 2015 pages have the apply button on them and so it still looks like you can apply for 2015 entry (eg for part-time study). Is there any way the 2015 pages can come down or a custom error 404 added to them to redirect people to the current UG course search? (that part could wait until the next booking but I think the banner needs to come down more urgently). Thanks
Angeal

**Comment by eg270-unikent** [comment]
@aw285-unikent I've rolled out the change to the banner just now. The 2014 pages are still live but are not linked to http://www.kent.ac.uk/courses/undergraduate/2014/ but as the pages are not linked to, users would need to go directly to these pages. I think a better option might be to remove the apply links from the 2014 and 2015 prospectus.

**Comment by aw285-unikent** [comment]
@eg270-unikent happy to remove the apply links and leave the pages up for reference if that is the idea behind keeping them live.

**Comment by eg270-unikent** [comment]
OK - I'll add it to our BAU backlog - can you let me know where it fits priority wise?

**Comment by aw285-unikent** [comment]
@eg270-unikent above 'notes field on programmes plant' - thanks, Angela

**Comment by eg270-unikent** [comment]
see #749 for action on this story. Closing this one.
