### ISSUE TITLE
Change 'Honours type' to 'Award type'

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#745]
As EMS

I would like to Change 'Honours type' to 'Award type' on the key facts to better reflect the nature of the content.

**Comment by eg270-unikent** [comment]
Is this for both UG and PG?

**Comment by aw285-unikent** [comment]
@eg270-unikent just UG please

**Comment by eg270-unikent** [comment]
Rolled out this morning. Closing.
