### ISSUE TITLE
Print style sheet

### ISSUE THREAD

**Issue by aw285-unikent** [unikent/of-course#92]
Hi making a note of a future story card/enhancement - reviewing the print style sheet for the programme pages.

**Comment by eg270-unikent** [comment]
HI @aw285-unikent is this something you would like us to pursue? Looks like the fees issue Lauren mentioned is still an issue.

**Comment by aw285-unikent** [comment]
Hi @eg270-unikent yes I think prettying up the print style for the course pages would be worth pursuing. Suggestions would be:

- Add Kent logo
- reviewing heading sizes
- giving users the option to print full module descriptions or just a list of modules [not sure how possible that is?] - as the module descriptions can heavily increase the page count. 
- moving key facts and fees to the first page before the overview
- removing most of the 'Enquire/order a prospectus section apart from the contact details. 
- removing the KIS widget section
- removing the 'learn more about Kent' section and images'
- removing the 'related to this course' list. 

@jt353-unikent may have thoughts on this?

Many thanks,

Angela

**Comment by eg270-unikent** [comment]
@aw285-unikent do you know who is using this?

**Comment by aw285-unikent** [comment]
@eg270-unikent just any users who want to print out the course information online rather than read it onscreen?

**Comment by jna-unikent** [comment]
@aw285-unikent unfortunately there is no easy way of allowing the user to choose whether or not to print the modules section. We can either include it or hide it altogether...

**Comment by aw285-unikent** [comment]
hi @jna-unikent probably best to include it then.

**Comment by jna-unikent** [comment]
@aw285-unikent unfortunately moving key facts and fees to the first page before the overview would be quite difficult. It would need rethinking the entire structure of how the course pages are put together. I'm not sure that the benefit would outweigh the cost here.

**Comment by aw285-unikent** [comment]
@jna-unikent no problem

**Comment by eg270-unikent** [comment]
@jna-unikent have these changes been rolled to test already?

**Comment by eg270-unikent** [comment]
These have been rolled to live this morning.
